### ISSUE TITLE
Docker container throws 500 error not working

### ISSUE THREAD

**Issue by jammi-shah** [eramba/docker#33]

**Comment by elsombrante** [comment]
Hello,

We need more information if you need help from us.

https://www.eramba.org/faqs#question-172

**Comment by willreddin** [comment]
Hello believe I'm having the same issue:

`
[php:error] [pid 26] [client 172.18.0.1:58630] PHP Fatal error:  [Cake\\Routing\\Exception\\MissingRouteException] A route matching "array (\n  'controller' => 'Settings',\n  'action' => 'getLogo',\n  'plugin' => false,\n  'prefix' => false,\n  0 => 'white',\n  '_ext' => NULL,\n)" could not be found.`

**Comment by shrkz1** [comment]
@jammi-shah @willreddin can you show your `docker logs eramba` output here? thanks

**Comment by jacksondaugherty** [comment]
Hi there,

I am experiencing a similar error when navigating to the site after the containers are up and running.  I've posted the following question in the community forum seeking assistance - https://discussions.eramba.org/t/question-post-install-php-errors.  I've run `docker logs eramba` and have pasted the output below.

```
sending incremental file list
emails/.gitkeep

sent 800 bytes  received 47 bytes  1,694.00 bytes/sec
total size is 0  speedup is 0.00
Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
In [/var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver.php, line 133]

2022-11-30 22:01:33 warning: Failed to create Incident archive because of an error: PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:84
Stack trace:
#0 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(84): PDO->__construct('mysql:host=mysq...', 'docker', '[redacted]', Array)
#1 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(152): Phinx\Db\Adapter\PdoAdapter->createPdoConnection('mysql:host=mysq...', 'docker', '[redacted]', Array)
#2 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(161): Phinx\Db\Adapter\MysqlAdapter->connect()
#3 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(476): Phinx\Db\Adapter\PdoAdapter->getConnection()
#4 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/CakeAdapter.php(50): Phinx\Db\Adapter\AdapterWrapper->getConnection()
#5 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(391): Migrations\CakeAdapter->__construct(Object(Phinx\Db\Adapter\TimedOutputAdapter), Object(Cake\Database\Connection))
#6 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(366): Migrations\Migrations->setAdapter()
#7 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(306): Migrations\Migrations->getManager(Object(Phinx\Config\Config))
#8 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(144): Migrations\Migrations->run('printStatus', Array, Object(Symfony\Component\Console\Input\ArrayInput))
#9 /var/www/eramba/app/upgrade/src/Application.php(1034): Migrations\Migrations->status(Array)
#10 /var/www/eramba/app/upgrade/plugins/Diagnostics/src/Error/Incident.php(136): App\Application::getDatabaseVersion()
#11 /var/www/eramba/app/upgrade/plugins/Diagnostics/src/Error/Incident.php(54): Diagnostics\Error\Incident->createArchiveFile()
#12 /var/www/eramba/app/upgrade/src/Error/ErrorLogger.php(74): Diagnostics\Error\Incident->log()
#13 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(334): App\Error\ErrorLogger->log(Object(Cake\Database\Exception\MissingConnectionException), NULL)
#14 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ConsoleErrorHandler.php(65): Cake\Error\BaseErrorHandler->logException(Object(Cake\Database\Exception\MissingConnectionException))
#15 [internal function]: Cake\Error\ConsoleErrorHandler->handleException(Object(Cake\Database\Exception\MissingConnectionException))
#16 {main}

Next InvalidArgumentException: There was a problem connecting to the database: SQLSTATE[HY000] [2002] Connection refused in /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:96
Stack trace:
#0 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(152): Phinx\Db\Adapter\PdoAdapter->createPdoConnection('mysql:host=mysq...', 'docker', '[redacted]', Array)
#1 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(161): Phinx\Db\Adapter\MysqlAdapter->connect()
#2 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(476): Phinx\Db\Adapter\PdoAdapter->getConnection()
#3 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/CakeAdapter.php(50): Phinx\Db\Adapter\AdapterWrapper->getConnection()
#4 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(391): Migrations\CakeAdapter->__construct(Object(Phinx\Db\Adapter\TimedOutputAdapter), Object(Cake\Database\Connection))
#5 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(366): Migrations\Migrations->setAdapter()
#6 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(306): Migrations\Migrations->getManager(Object(Phinx\Config\Config))
#7 /var/www/eramba/app/upgrade/vendor/cakephp/migrations/src/Migrations.php(144): Migrations\Migrations->run('printStatus', Array, Object(Symfony\Component\Console\Input\ArrayInput))
#8 /var/www/eramba/app/upgrade/src/Application.php(1034): Migrations\Migrations->status(Array)
#9 /var/www/eramba/app/upgrade/plugins/Diagnostics/src/Error/Incident.php(136): App\Application::getDatabaseVersion()
#10 /var/www/eramba/app/upgrade/plugins/Diagnostics/src/Error/Incident.php(54): Diagnostics\Error\Incident->createArchiveFile()
#11 /var/www/eramba/app/upgrade/src/Error/ErrorLogger.php(74): Diagnostics\Error\Incident->log()
#12 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(334): App\Error\ErrorLogger->log(Object(Cake\Database\Exception\MissingConnectionException), NULL)
#13 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ConsoleErrorHandler.php(65): Cake\Error\BaseErrorHandler->logException(Object(Cake\Database\Exception\MissingConnectionException))
#14 [internal function]: Cake\Error\ConsoleErrorHandler->handleException(Object(Cake\Database\Exception\MissingConnectionException))
#15 {main}
2022-11-30 22:01:33 error: [Cake\Database\Exception\MissingConnectionException] Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused in /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver.php on line 133
Stack Trace:
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:164
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Schema/SchemaDialect.php:51
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:216
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:53
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Connection.php:395
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Table.php:512
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Query.php:290
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Query.php:184
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Table.php:1699
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Table.php:1263
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Model/Table/QueueProcessesTable.php:130
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Model/Table/QueueProcessesTable.php:241
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Command/WorkerCommand.php:107
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Command/WorkerCommand.php:96
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /var/www/eramba/app/upgrade/bin/cake.php:12

Caused by: [PDOException] SQLSTATE[HY000] [2002] Connection refused in /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver.php on line 125
Stack Trace:
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver.php:125
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver.php:131
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:164
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Schema/SchemaDialect.php:51
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:216
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:53
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Database/Connection.php:395
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Table.php:512
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Query.php:290
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Query.php:184
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Table.php:1699
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/ORM/Table.php:1263
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Model/Table/QueueProcessesTable.php:130
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Model/Table/QueueProcessesTable.php:241
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Command/WorkerCommand.php:107
- /var/www/eramba/app/upgrade/vendor/dereuromark/cakephp-queue/src/Command/WorkerCommand.php:96
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /var/www/eramba/app/upgrade/bin/cake.php:12



Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Waiting for database...
Connection to Mysql could not be established: SQLSTATE[HY000] [2002] Connection refused
Using connection: default
Dry-run mode: disabled
-------------------------------------------------------------------------------
Failed to connect to the database, exiting...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
[Wed Nov 30 22:01:53.735898 2022] [ssl:warn] [pid 1] AH01909: 172.26.0.4:443:0 server certificate does NOT include an ID which matches the server name
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
[Wed Nov 30 22:01:53.758910 2022] [ssl:warn] [pid 1] AH01909: 172.26.0.4:443:0 server certificate does NOT include an ID which matches the server name
[Wed Nov 30 22:01:53.761899 2022] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.53 (Debian) PHP/8.1.7 OpenSSL/1.1.1n configured -- resuming normal operations
[Wed Nov 30 22:01:53.761939 2022] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Wed Nov 30 22:03:56.922070 2022] [php:error] [pid 26] [client 172.20.20.75:56438] PHP Fatal error:  [Cake\\Routing\\Exception\\MissingRouteException] A route matching "array (\n  'controller' => 'Settings',\n  'action' => 'getLogo',\n  'plugin' => false,\n  'prefix' => false,\n  0 => 'white',\n  '_ext' => NULL,\n)" could not be found. (/var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:326)\n#0 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/Router.php(497): Cake\\Routing\\RouteCollection->match(Array, Array)\n#1 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(45): Cake\\Routing\\Router::url(Array, true)\n#2 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(21): App\\View\\Helper\\LogoHelper->url(Array)\n#3 /var/www/eramba/app/upgrade/templates/layout/error.php(64): App\\View\\Helper\\LogoHelper->render()\n#4 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1181): include('/var/www/eramba...')\n#5 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1138): Cake\\View\\View->_evaluate('/var/www/eramba...', Array)\n#6 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(821): Cake\\View\\View->_render('/var/www/eramba...')\n#7 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(780): Cake\\View\\View->renderLayout('', 'error')\n#8 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Controller/Controller.php(764): Cake\\View\\View->render()\n#9 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(392): Cake\\Controller\\Controller->render('error500')\n#10 /var/www/eramba/app/upgrade/vendor/mixerapi/exception-render/src/MixerApiExceptionRenderer.php(100): Cake\\Error\\ExceptionRenderer->_outputMessage('error500')\n#11 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(138): MixerApi\\ExceptionRender\\MixerApiExceptionRenderer->render()\n#12 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(218): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Error\\FatalErrorException))\n#13 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(257): Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Error\\FatalErrorException))\n#14 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(155): Cake\\Error\\BaseErrorHandler->handleFatalError(256, '[Cake\\\\Routing\\\\E...', '/var/www/eramba...', 196)\n#15 [internal function]: Cake\\Error\\BaseErrorHandler->handleError(256, '[Cake\\\\Routing\\\\E...', '/var/www/eramba...', 196)\n#16 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(196): trigger_error('[Cake\\\\Routing\\\\E...', 256)\n#17 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(141): Cake\\Error\\ErrorHandler->_logInternalError(Object(Cake\\Routing\\Exception\\MissingRouteException))\n#18 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(218): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Routing\\Exception\\MissingRouteException))\n#19 [internal function]: Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Database\\Exception\\DatabaseException))\n#20 {main} in /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196
[Wed Nov 30 22:03:56.923775 2022] [php:error] [pid 26] [client 172.20.20.75:56438] PHP Fatal error:  [Cake\\Routing\\Exception\\MissingRouteException] A route matching "array (\n  'controller' => 'Settings',\n  'action' => 'getLogo',\n  'plugin' => false,\n  'prefix' => false,\n  0 => 'white',\n  '_ext' => NULL,\n)" could not be found. (/var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:326)\n#0 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/Router.php(497): Cake\\Routing\\RouteCollection->match(Array, Array)\n#1 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(45): Cake\\Routing\\Router::url(Array, true)\n#2 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(21): App\\View\\Helper\\LogoHelper->url(Array)\n#3 /var/www/eramba/app/upgrade/templates/layout/error.php(64): App\\View\\Helper\\LogoHelper->render()\n#4 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1181): include('/var/www/eramba...')\n#5 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1138): Cake\\View\\View->_evaluate('/var/www/eramba...', Array)\n#6 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(821): Cake\\View\\View->_render('/var/www/eramba...')\n#7 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(780): Cake\\View\\View->renderLayout('', 'error')\n#8 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Controller/Controller.php(764): Cake\\View\\View->render()\n#9 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(392): Cake\\Controller\\Controller->render('error500')\n#10 /var/www/eramba/app/upgrade/vendor/mixerapi/exception-render/src/MixerApiExceptionRenderer.php(100): Cake\\Error\\ExceptionRenderer->_outputMessage('error500')\n#11 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(138): MixerApi\\ExceptionRender\\MixerApiExceptionRenderer->render()\n#12 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(218): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Error\\FatalErrorException))\n#13 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(257): Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Error\\FatalErrorException))\n#14 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(119): Cake\\Error\\BaseErrorHandler->handleFatalError(256, '[Cake\\\\Routing\\\\E...', '/var/www/eramba...', 196)\n#15 [internal function]: Cake\\Error\\BaseErrorHandler->Cake\\Error\\{closure}()\n#16 {main} in /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196
172.20.20.75 - - [30/Nov/2022:22:03:56 +0000] "GET / HTTP/1.1" 500 2831 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[Wed Nov 30 22:03:57.167413 2022] [php:error] [pid 29] [client 172.20.20.75:56441] PHP Fatal error:  [Cake\\Routing\\Exception\\MissingRouteException] A route matching "array (\n  'controller' => 'Settings',\n  'action' => 'getLogo',\n  'plugin' => false,\n  'prefix' => false,\n  0 => 'white',\n  '_ext' => NULL,\n)" could not be found. (/var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:326)\n#0 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/Router.php(497): Cake\\Routing\\RouteCollection->match(Array, Array)\n#1 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(45): Cake\\Routing\\Router::url(Array, true)\n#2 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(21): App\\View\\Helper\\LogoHelper->url(Array)\n#3 /var/www/eramba/app/upgrade/templates/layout/error.php(64): App\\View\\Helper\\LogoHelper->render()\n#4 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1181): include('/var/www/eramba...')\n#5 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1138): Cake\\View\\View->_evaluate('/var/www/eramba...', Array)\n#6 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(821): Cake\\View\\View->_render('/var/www/eramba...')\n#7 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(780): Cake\\View\\View->renderLayout('', 'error')\n#8 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Controller/Controller.php(764): Cake\\View\\View->render()\n#9 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(392): Cake\\Controller\\Controller->render('error500')\n#10 /var/www/eramba/app/upgrade/vendor/mixerapi/exception-render/src/MixerApiExceptionRenderer.php(100): Cake\\Error\\ExceptionRenderer->_outputMessage('error500')\n#11 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(138): MixerApi\\ExceptionRender\\MixerApiExceptionRenderer->render()\n#12 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(218): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Error\\FatalErrorException))\n#13 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(257): Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Error\\FatalErrorException))\n#14 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(155): Cake\\Error\\BaseErrorHandler->handleFatalError(256, '[Cake\\\\Routing\\\\E...', '/var/www/eramba...', 196)\n#15 [internal function]: Cake\\Error\\BaseErrorHandler->handleError(256, '[Cake\\\\Routing\\\\E...', '/var/www/eramba...', 196)\n#16 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(196): trigger_error('[Cake\\\\Routing\\\\E...', 256)\n#17 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(141): Cake\\Error\\ErrorHandler->_logInternalError(Object(Cake\\Routing\\Exception\\MissingRouteException))\n#18 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(218): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Routing\\Exception\\MissingRouteException))\n#19 [internal function]: Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Database\\Exception\\DatabaseException))\n#20 {main} in /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196
[Wed Nov 30 22:03:57.169099 2022] [php:error] [pid 29] [client 172.20.20.75:56441] PHP Fatal error:  [Cake\\Routing\\Exception\\MissingRouteException] A route matching "array (\n  'controller' => 'Settings',\n  'action' => 'getLogo',\n  'plugin' => false,\n  'prefix' => false,\n  0 => 'white',\n  '_ext' => NULL,\n)" could not be found. (/var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/RouteCollection.php:326)\n#0 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Routing/Router.php(497): Cake\\Routing\\RouteCollection->match(Array, Array)\n#1 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(45): Cake\\Routing\\Router::url(Array, true)\n#2 /var/www/eramba/app/upgrade/src/View/Helper/LogoHelper.php(21): App\\View\\Helper\\LogoHelper->url(Array)\n#3 /var/www/eramba/app/upgrade/templates/layout/error.php(64): App\\View\\Helper\\LogoHelper->render()\n#4 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1181): include('/var/www/eramba...')\n#5 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(1138): Cake\\View\\View->_evaluate('/var/www/eramba...', Array)\n#6 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(821): Cake\\View\\View->_render('/var/www/eramba...')\n#7 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/View/View.php(780): Cake\\View\\View->renderLayout('', 'error')\n#8 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Controller/Controller.php(764): Cake\\View\\View->render()\n#9 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(392): Cake\\Controller\\Controller->render('error500')\n#10 /var/www/eramba/app/upgrade/vendor/mixerapi/exception-render/src/MixerApiExceptionRenderer.php(100): Cake\\Error\\ExceptionRenderer->_outputMessage('error500')\n#11 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(138): MixerApi\\ExceptionRender\\MixerApiExceptionRenderer->render()\n#12 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(218): Cake\\Error\\ErrorHandler->_displayException(Object(Cake\\Error\\FatalErrorException))\n#13 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(257): Cake\\Error\\BaseErrorHandler->handleException(Object(Cake\\Error\\FatalErrorException))\n#14 /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(119): Cake\\Error\\BaseErrorHandler->handleFatalError(256, '[Cake\\\\Routing\\\\E...', '/var/www/eramba...', 196)\n#15 [internal function]: Cake\\Error\\BaseErrorHandler->Cake\\Error\\{closure}()\n#16 {main} in /var/www/eramba/app/upgrade/vendor/cakephp/cakephp/src/Error/ErrorHandler.php on line 196
172.20.20.75 - - [30/Nov/2022:22:03:57 +0000] "GET / HTTP/1.1" 500 2831 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```

Any help is appreciated!

**Comment by shrkz1** [comment]
i dont think this is an issue anymore
